version: '3'
services:
  prometheus:
    image: bitnami/prometheus:2.55.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml