scrape_configs:
  - job_name: 'prometheus_demo'
    scrape_interval: 5s
    scrape_timeout: 3s
    static_configs:
      - targets: ["192.168.10.232:8081"]
#        192.168.10.232  30.116.184.138
#  - job_name: "node_exporter"
#    scrape_interval: 5s
#    static_configs:
#      - targets: ["node-exporter:9100"]