// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"prometheusdemo/internal/repository"
	"prometheusdemo/internal/repository/dao"
	"prometheusdemo/internal/service"
	"prometheusdemo/internal/web"
	"prometheusdemo/ioc"
)

// Injectors from wire.go:

func InitializeApp() *App {
	v := ioc.InitGinMiddlewares()
	mysqlConfig := ioc.InitMysqlConfig()
	db := ioc.InitDB(mysqlConfig)
	userDAO := dao.NewUserDAO(db)
	userRepository := repository.NewCacheUserRepository(userDAO)
	userService := service.NewUserService(userRepository)
	userHandler := web.NewUserHandler(userService)
	engine := ioc.InitWebServer(v, userHandler)
	app := &App{
		server: engine,
	}
	return app
}
