version: '3.8'

services:
  kafka:
    image: bitnami/kafka:3.9.0
    container_name: kafka
    environment:
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.137.89:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LOG_DIRS=/bitnami/kafka/data
      - KAFKA_CFG_ZOOKEEPER_CONNECT=
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_CFG_NODE_ID=1  # 设置唯一的节点ID
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=PLAINTEXT_HOST  # 设置控制器监听器名称
    volumes:
      - kafka_data:/bitnami/kafka/data
    ports:
      - 9092:9092
    networks:
      - kafka_network
  emqx:
    image: emqx:5.8.4
    container_name: emqx-test
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    restart: always
    networks:
      kafka_network:
    volumes:
      - emqx-emqx-data:/opt/emqx/data
      - emqx-emqx-etc:/opt/emqx/etc
      - emqx-emqx-log:/opt/emqx/log
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "18083:18083"
      - "8883:8883"
    environment:
      - TZ=Asia/Shanghai
  mqtt_kafka_mdl:
    image: mqtt_kafka_mdl:1.0
    ports:
      - "8086:8080"
    networks:
      kafka_network:


volumes:
  kafka_data:
  emqx-emqx-data:
  emqx-emqx-etc:
  emqx-emqx-log:


networks:
  kafka_network: