version: "3"
services:
  etcd:
    image: bitnami/etcd:3.6.1
    ports:
      - "2379:2379"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379,http://localhost:2379
    volumes:
      - etcd_data:/bitnami/etcd

volumes:
  etcd_data: