// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/basicprojectv2/user_service/ioc"
	"github.com/basicprojectv2/user_service/repository"
	"github.com/basicprojectv2/user_service/repository/dao"
	"github.com/basicprojectv2/user_service/service"
	"github.com/basicprojectv2/user_service/settings"
)

// Injectors from wire.go:

func InitializeApp() *App {
	mysqlConfig := settings.InitMysqlConfig()
	db := ioc.InitDB(mysqlConfig)
	userDAO := dao.NewUserDAO(db)
	userRepository := repository.NewUserRepository(userDAO)
	userService := service.NewUserService(userRepository)
	mainUserService := NewUerService(userService)
	etcdConfig := ioc.NewEtcdConfig()
	app := NewApp(mainUserService, etcdConfig)
	return app
}
