version: '3.7'
services:
  db:
    image: 'mysql:8.0'
    container_name: 'basic-project-mysql'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: webook
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - '13306:3306'
  redis:
    image: 'redis:7.2.3'
    container_name: 'basic_project_redis'
    ports:
      - '16379:6379'
  backend:
    depends_on:
      - redis
      - db
    image: 'basic_project:v1'
    container_name: 'basic-project'
    ports:
      - '8085:8085'
    restart: always