version: '3.7'
services:
  db:
    image: 'mysql:8.0'
    container_name: 'basic-project-mysql'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: webook
    # 要确保要挂载的目录存在且有正确的读取权限
    volumes:
      - /var/lib/mysql
    ports:
      - '13306:3306'
  redis:
    image: 'redis:7.2.3'
    container_name: 'basic_project_redis'
    ports:
      - '16379:6379'
  backend:
    depends_on:
      - redis
      - db
    image: 'basic_project:v1'
    container_name: 'basic-project'
    ports:
      - '8083:8000'
    restart: always
  frontend:
    depends_on:
      - backend
    image: 'basic_project_frontend_compose:v1'
    container_name: 'basic_project_frontend_compose'
    environment:
      - VUE_APP_BASE_API=http://30.116.184.138:8083
    ports:
      - '8080:80'
