apiVersion: v1
kind: Service
metadata:
  name: basic
spec:
  type: LoadBalancer
  selector:
    app: basic
  ports:
    - name: http
      port: 8085
      protocol: TCP
      targetPort: 8000

---
apiVersion: apps/v1
kind : Deployment
metadata:
  name: basic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic
  template:
    metadata:
      labels:
        app: basic
    spec:
      containers:
        - name: basic
          image: basic_project:v1
          ports:
            - containerPort: 8000