apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-demo
spec:
  rules:
    - host: basicproject.me.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: basic-project
                port:
                  number: 8085
