apiVersion: v1
kind: Service
metadata:
  name: basic-project
spec:
  type: LoadBalancer
  selector:
    app: basic-project
  ports:
    - name: http
      port: 8086
      protocol: TCP
      targetPort: 8086

---
apiVersion: apps/v1
kind : Deployment
metadata:
  name: basic-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic-project
  template:
    metadata:
      labels:
        app: basic-project
    spec:
      containers:
        - name: basic-project
          image: basic_project:v1
          ports:
            - containerPort: 8086