// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: user.proto

package service

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Userid        string                 `protobuf:"bytes,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Age           string                 `protobuf:"bytes,3,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUserid() string {
	if x != nil {
		return x.Userid
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

type GetUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReq) Reset() {
	*x = GetUserReq{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReq) ProtoMessage() {}

func (x *GetUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReq.ProtoReflect.Descriptor instead.
func (*GetUserReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CircuitBrakerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       int32                  `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"` // 拦截器逻辑
	Manual        int32                  `protobuf:"varint,2,opt,name=manual,proto3" json:"manual,omitempty"`   // 手动控制
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CircuitBrakerReq) Reset() {
	*x = CircuitBrakerReq{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CircuitBrakerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CircuitBrakerReq) ProtoMessage() {}

func (x *CircuitBrakerReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CircuitBrakerReq.ProtoReflect.Descriptor instead.
func (*CircuitBrakerReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *CircuitBrakerReq) GetEnabled() int32 {
	if x != nil {
		return x.Enabled
	}
	return 0
}

func (x *CircuitBrakerReq) GetManual() int32 {
	if x != nil {
		return x.Manual
	}
	return 0
}

type CircuitBrakerResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       int32                  `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"` // 拦截器逻辑
	Manual        int32                  `protobuf:"varint,2,opt,name=manual,proto3" json:"manual,omitempty"`   // 手动控制
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CircuitBrakerResp) Reset() {
	*x = CircuitBrakerResp{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CircuitBrakerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CircuitBrakerResp) ProtoMessage() {}

func (x *CircuitBrakerResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CircuitBrakerResp.ProtoReflect.Descriptor instead.
func (*CircuitBrakerResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *CircuitBrakerResp) GetEnabled() int32 {
	if x != nil {
		return x.Enabled
	}
	return 0
}

func (x *CircuitBrakerResp) GetManual() int32 {
	if x != nil {
		return x.Manual
	}
	return 0
}

type CoreResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreResp) Reset() {
	*x = CoreResp{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreResp) ProtoMessage() {}

func (x *CoreResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreResp.ProtoReflect.Descriptor instead.
func (*CoreResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *CoreResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\fuser_service\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"L\n" +
	"\x04User\x12\x16\n" +
	"\x06userid\x18\x01 \x01(\tR\x06userid\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x10\n" +
	"\x03age\x18\x03 \x01(\tR\x03age\"\x1c\n" +
	"\n" +
	"GetUserReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x10CircuitBrakerReq\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\x05R\aenabled\x12\x16\n" +
	"\x06manual\x18\x02 \x01(\x05R\x06manual\"E\n" +
	"\x11CircuitBrakerResp\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\x05R\aenabled\x12\x16\n" +
	"\x06manual\x18\x02 \x01(\x05R\x06manual\"\x1c\n" +
	"\bCoreResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2\xa4\x02\n" +
	"\vUserService\x12R\n" +
	"\vGetUserById\x12\x18.user_service.GetUserReq\x1a\x12.user_service.User\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/user/{id}\x12r\n" +
	"\x14ControlCircuitBraker\x12\x1e.user_service.CircuitBrakerReq\x1a\x1f.user_service.CircuitBrakerResp\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/circuitbraker\x12M\n" +
	"\fCoreBusiness\x12\x16.google.protobuf.Empty\x1a\x16.user_service.CoreResp\"\r\x82\xd3\xe4\x93\x02\a\x12\x05/coreB\fZ\n" +
	"../serviceb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_user_proto_goTypes = []any{
	(*User)(nil),              // 0: user_service.User
	(*GetUserReq)(nil),        // 1: user_service.GetUserReq
	(*CircuitBrakerReq)(nil),  // 2: user_service.CircuitBrakerReq
	(*CircuitBrakerResp)(nil), // 3: user_service.CircuitBrakerResp
	(*CoreResp)(nil),          // 4: user_service.CoreResp
	(*emptypb.Empty)(nil),     // 5: google.protobuf.Empty
}
var file_user_proto_depIdxs = []int32{
	1, // 0: user_service.UserService.GetUserById:input_type -> user_service.GetUserReq
	2, // 1: user_service.UserService.ControlCircuitBraker:input_type -> user_service.CircuitBrakerReq
	5, // 2: user_service.UserService.CoreBusiness:input_type -> google.protobuf.Empty
	0, // 3: user_service.UserService.GetUserById:output_type -> user_service.User
	3, // 4: user_service.UserService.ControlCircuitBraker:output_type -> user_service.CircuitBrakerResp
	4, // 5: user_service.UserService.CoreBusiness:output_type -> user_service.CoreResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
