version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.19.12
    container_name: simple_es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    ports:
      - "9200:9200"