name: "basicproject"
mode: "prod"
port: 8086
version: "v0.0.1"

mysql:
  host: "192.168.2.119"
  port: 3309
  user: "root"
  password: "12345678"
  dbname: "webook"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "192.168.2.119"
  port: 16379