name: "basicproject"
mode: "prod"
port: 8081
version: "v0.0.1"

mysql:
  host: "30.116.184.138"
  port: 3308
  user: "root"
  password: "12345678"
  dbname: "webook"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "30.116.184.138"
  port: 6380