name: "basicproject"
mode: "dev"
port: 8081
version: "v0.0.1"

mysql:
  host: "basic-project-mysql"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "webook"
  max_open_conns: 200
  max_idle_conns: 50